---
- hosts: all
  user: root
  tasks:
  - name: Install nginx is a high performance web server
    yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm state=present
    action: command cp /etc/nginx/nginx.conf{,.original}
