#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###################################
# git branch merge
# Author: netkiller@msn.com
# Home:	http://www.netkiller.cn
###################################
# zentaoclose $(date -d "-15 day" "+%Y-%m-%d")
###################################
try:
    import subprocess
    import re
    import sys
    import requests
except ImportError as err:
    print("Error: %s" % (err))

if len(sys.argv) == 1:
    exit()
date = sys.argv[1]

api_address = 'http://zentao.netkiller.cn/zentao/gitlab.php'


def zentao(type, id):
    url = api_address + \
        "?id={id}&type={type}&func=close".format(id=id, type=type)
    request = requests.get(url)
    if request.status_code == 200:
        id, status = request.text.split(', ')
        # print(id, status)
        if status != '0':
            print(request.status_code, request.reason, id, status)


commit = subprocess.getoutput(
    'git log --no-merges --pretty=format:"%s" --since={date} | egrep "BUG|TASK"'.format(date=date))

tasks = set()

for id in re.findall(r"TASK#(\d+)\s", commit, re.M):
    tasks.add(id)
for id in re.findall(r"TASK\s#(\d+)\s", commit, re.M):
    tasks.add(id)
# ids.extend(re.findall(r"\[TASK\s#(\d+)\]", commit, re.M))
tasks = sorted(tasks)
print('TASK', tasks)
for task in tasks:
    zentao('task', task)

bugs = set()
for id in re.findall(r"BUG #(\d+)\s", commit, re.M):
    bugs.add(id)
bugs = sorted(bugs)
print('BUG', bugs)
for bug in bugs:
    zentao('bug', bug)
