#! /usr/bin/env python3
# -*- coding: UTF-8 -*-
##############################################
# Home	: https://www.netkiller.cn
# Author: Neo <netkiller@msn.com>
# Help  : https://github.com/netkiller/devops/blob/master/doc/zentao.md
##############################################

import sys
import re
import requests
import json

zentao = 'https://zentao.netkiller.cn'


def title(type, id):
    value = None
    if type == 'BUG':
        url = zentao + '/zentao/bug-view-'+str(id)+'.json'
    elif type == 'TASK':
        url = zentao + '/zentao/task-view-' + str(id) + '.json'
    elif type == 'STORY':
        url = zentao + '/zentao/story-view-' + str(id) + '.json'
    elif type == 'FEEDBACK':
        url = zentao + '/zentao/feedback-view-' + str(id) + '.json'
    else:
        url = zentao + '/zentao/doc-view-' + str(id) + '.json'

    request = requests.get(url)
    # print(request.text)
    # print(json.loads(request.content.decode()))

    try:
        json_string = request.json()
        if json_string['status'] == 'success':
            data = json.loads(json_string['data'])
            value = data['title']
    except requests.exceptions.JSONDecodeError:
        value = None

    return (value)


def numbers(msg):
    ids = ids = re.findall(re.compile(r"\d+"), msg)
    return ids


def format(msg):
    message = ''
    if msg.find('BUG') >= 0:
        # message,group = re.subn(re.compile(r"(BUG)\s+(\d+)"), r'\1 http://zentao.ejiayou.com/zentao/bug-view-\2.html', msg)
        # message, group = re.subn(re.compile(r"(\d+)"), rzentao + '/zentao/bug-view-\1.html', msg)
        ids = numbers(msg)
        for id in ids:
            bug = title('BUG', id)
            if bug:
                # msg = msg.replace( id, "[{title}]({zentao}/zentao/bug-view-{id}.html)\n".format(id=id, title=bug, zentao=zentao))
                message += "[{title}]({zentao}/zentao/bug-view-{id}.html)\n".format(
                    id=id, title=bug, zentao=zentao)
            else:
                message += "[BUG #{id}]\n".format(id=id)

    elif msg.find('TASK') >= 0:
        ids = numbers(msg)
        for id in ids:
            task = title('TASK', id)
            if task:
                # msg = msg.replace(                   id, "[{title}]("+zentao + "/zentao/task-view-{id}.html)".format(id=id, title=task))
                message += "[{title}]({zentao}/zentao/task-view-{id}.html)\n".format(
                    id=id, title=task, zentao=zentao)
            else:
                message += "[TASK #{id}]\n".format(id=id)
        # message, group = re.subn(re.compile(r"(\d+)"), rzentao + '/zentao/task-view-\1.html' + ' (' + title + ')', msg)
    elif msg.find('DOC') >= 0:
        ids = numbers(msg)
        for id in ids:
            task = title('DOC', id)
            if task:
                message += "[{title}]({zentao}/zentao/doc-view-{id}.html)\n".format(
                    id=id, title=task, zentao=zentao)
            else:
                message += "[DOC #{id}]\n".format(id=id)
    elif msg.find('DOC') >= 0:
        ids = numbers(msg)
        for id in ids:
            doc = title('DOC', id)
            if doc:
                message += "[{title}]({zentao}/zentao/doc-view-{id}.html)\n".format(
                    id=id, title=doc, zentao=zentao)
            else:
                message += "[DOC #{id}]\n".format(id=id)
    elif msg.find('STORY') >= 0:
        ids = numbers(msg)
        for id in ids:
            story = title('STORY', id)
            if story:
                message += "[{title}]({zentao}/zentao/story-view-{id}.html)\n".format(
                    id=id, title=story, zentao=zentao)
            else:
                message += "[STORY #{id}]\n".format(id=id)
    elif msg.find('FEEDBACK') >= 0:
        ids = numbers(msg)
        for id in ids:
            feedback = title('FEEDBACK', id)
            if feedback:
                message += "[{title}]({zentao}/zentao/feedback-view-{id}.html)\n".format(
                    id=id, title=feedback, zentao=zentao)
            else:
                message += "[FEEDBACK #{id}]\n".format(id=id)
    else:
        message += message += re.sub(r'(TMP|MSG)\s', "", msg)

    return message


def check(msg):
    lists = re.findall(re.compile(r"(BUG|TASK|DOC|TMP|STORY|FEEDBACK|MSG|Merge)"), msg)
    if not lists:
        print("提交格式错误，请以BUG或TASK开头，然后填写该任务或BUG号码，多个编号使用空格分割，清参考：")
        print("BUG 1024 2048 4096")
        print("TASK 1024 2048 4096")
        print("DOC 11 22 33")
        print("https://github.com/netkiller/devops/blob/master/doc/zentao.md")
        exit(1)


if len(sys.argv) == 2:
    filename = sys.argv[1]
    file = open(filename, 'r', encoding='utf-8')
    check(file.read())
    file.seek(0)
    lines = file.readlines()
    file.close()

    message = ''
    for line in lines:
        message += format(line)

    file = open(filename, 'w', encoding='utf-8')
    file.write(message)
    file.flush()
    file.close()
    exit(0)
else:
    exit(1)
